import { GlobalStyles } from '@/app/global'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

const notoSansKR = Noto_Sans_KR({
  weight: ['300', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <head>
        <title>웹 프론트엔드 이력서 - 오이슬</title>
      </head>

      <body className={notoSansKR.className}>
        <GlobalStyles />
        {children}
      </body>
    </html>
  )
}
